import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { NavbarComponent } from "../components/navbar/NavbarComponent";
import { Footer } from "flowbite-react";
import { FooterComponent } from "../components/home/FooterComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-100">
        <header>
          <NavbarComponent />
        </header>
        {children}
        <Footer>
          <FooterComponent />
        </Footer>
      </body>
    </html>
  );
}
